name: build
on:
  push:
    tags:
      - '*'

jobs:
  build:
    permissions:
      contents: write

    runs-on: ubuntu-latest
    steps:
      - name: download repo
        uses: actions/checkout@v4

      - name: run build
        run: |
          sudo ./build.sh

      - name: create release
        uses: soap-phia/gh-large-releases@a
        with:
          draft: true
          files: out/*.zip
